name: Publish FandaUI Library

on:
  push:
    branches:
      - main
    paths:
      - "projects/fanda-ui/**"
      - ".github/workflows/publish.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          registry-url: https://npm.pkg.github.com

      - name: Replace {TOKEN} in .npmrc
        run: |
          $content = Get-Content -Path .npmrc -Raw
          $content -replace '{GITHUB_TOKEN}', '${{ secrets.PACKAGE_TOKEN }}'
          Set-Content -Path .npmrc -Value $content
        shell: pwsh

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the library
      - name: Build FandaUI Library
        run: npm run build:lib

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fanda-ui
          path: dist/

  PublishNPM:
    needs: Build
    if: needs.Build.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: fanda-ui

      - name: Replace {TOKEN} in .npmrc
        run: |
          $content = Get-Content -Path .npmrc -Raw
          $content -replace '{GITHUB_TOKEN}', '${{ secrets.PACKAGE_TOKEN }}'
          Set-Content -Path .npmrc -Value $content
        shell: pwsh

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          registry-url: "https://npm.pkg.github.com"
          scope: "@fanda-org"

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
